# ==============================================================================
# GitHub Actions Workflow to build a STATIC OpenSSH package for OpenWrt
# using the source compilation Dockerfile.
# ==============================================================================

name: Build Static OpenSSH Package for OpenWrt (ARMv5)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-static-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the static OpenSSH package using Dockerfile
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t openssh-static-package \
            --output type=docker \
            .

      - name: Extract final tarball from the image
        run: |
          mkdir -p ./openssh-dist
          # Create a temporary container from the final image
          id=$(docker create openssh-static-package)
          # Copy the single tar.gz file from the container's root
          docker cp "$id:/openssh-static-armel.tar.gz" ./openssh-dist/
          # Clean up the container
          docker rm -v "$id"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openssh-static-armel-package
          path: ./openssh-dist/
