# ==============================================================================
# GitHub Actions Workflow to build an ULTRA-CUSTOM OpenWrt ROOTFS for LXC
# Version: The Ultimate Virtualization Build, targeting 'armvirt' for max compatibility.
# ==============================================================================

name: Build OpenWrt RootFS for ARM Virtualized Env (LXC)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-rootfs:
    runs-on: ubuntu-latest

    env:
      # We will use a modern, stable version that has excellent virt support.
      OPENWRT_VERSION: 23.05.3
      # (KEY CHANGE) Targeting the ARM Virtualization platform.
      OPENWRT_TARGET: armvirt
      OPENWRT_SUBTARGET: 32
      OPENWRT_DOWNLOAD_URL_BASE: https://downloads.openwrt.org/releases

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential libncurses5-dev libncursesw5-dev \
            zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget

      - name: Download and set up the 'armvirt' Image Builder
        run: |
          IMAGE_BUILDER_URL="${OPENWRT_DOWNLOAD_URL_BASE}/${OPENWRT_VERSION}/targets/${OPENWRT_TARGET}/${OPENWRT_SUBTARGET}/openwrt-imagebuilder-${OPENWRT_VERSION}-${OPENWRT_TARGET}-${OPENWRT_SUBTARGET}.Linux-x86_64.tar.xz"
          echo "--- Downloading 'armvirt' Image Builder from: ${IMAGE_BUILDER_URL} ---"
          wget --tries=5 --retry-connrefused "${IMAGE_BUILDER_URL}" -O imagebuilder.tar.xz
          tar -xJvf imagebuilder.tar.xz
          cd openwrt-imagebuilder-*
          make info

      - name: Build custom ultra-minimal rootfs
        run: |
          cd openwrt-imagebuilder-*
          # 'armvirt' only has a 'generic' profile, so we can hardcode it.
          PROFILE="generic"
          
          PACKAGES=" \
            -dropbear \
            openssh-server \
            -network \
            -ppp -ppp-mod-pppoe \
            -firewall4 -nftables \
            -odhcp6c -odhcpd-ipv6only \
            -luci* \
            -dnsmasq \
            -wpad-basic-wolfssl \
            -iwinfo \
            -logd \
            -urngd \
            -ucode \
          "
          echo "--- Building 'armvirt' firmware with packages: ${PACKAGES} ---"
          
          make image \
            PROFILE="${PROFILE}" \
            PACKAGES="${PACKAGES}"
          
          echo "--- Manually creating rootfs tarball ---"
          cd build_dir/target-*/root-*
          tar -czf ../openwrt-rootfs-manual.tar.gz .
          echo "--- Rootfs tarball created successfully ---"

      - name: Upload RootFS artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-armvirt-rootfs-armel
          path: openwrt-imagebuilder-*/build_dir/target-*/openwrt-rootfs-manual.tar.gz
          if-no-files-found: error
