name: test

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 1440
    steps:
    # 步骤 1: 安装中文语言包（使用更兼容的方法）
    - name: Install Chinese Language Pack
      run: |
        # 使用 PowerShell 安装语言包
        $LanguagePack = "zh-CN"
        
        # 方法1: 尝试使用 Add-WindowsCapability
        try {
            Add-WindowsCapability -Online -Name "Language.Basic~~~zh-CN~0.0.1.0"
        } catch {
            Write-Host "Add-WindowsCapability method failed, trying alternative..."
        }
        
        # 设置区域和语言设置
        Set-WinSystemLocale -SystemLocale zh-CN
        Set-Culture -CultureInfo zh-CN
        


    # 步骤 2: 启用远程桌面 (RDP)
    - name: Enable TS
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    # 步骤 3: 设置用户密码（使用 Secret）
    - name: Set User Password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "${{ secrets.RDP_PASSWORD }}" -Force)

    # 步骤 4: 创建 SSH 私钥文件
    - name: Create SSH Key
      run: |
        New-Item -ItemType Directory -Force -Path .ssh
        Set-Content -Path ".ssh\id_ed25519" -Value "${{ secrets.SSH_PRIVATE_KEY }}"
        icacls ".ssh\id_ed25519" /inheritance:r /grant "$env:USERNAME:R"

    # 步骤 5: 启动 SSH 隧道
    - name: Start SSH Tunnel
      run: |
        Start-Process -FilePath "ssh.exe" -WindowStyle Hidden -ArgumentList "-i", ".ssh\id_ed25519", "-p", "${{ secrets.SSH_PORT }}", "-fNR", "13389:localhost:3389", "-o", "StrictHostKeyChecking=no", "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}"
        Start-Sleep -s 21800
