name: test

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 1440
    steps:
    # 步骤 1: 下载文件
    - name: Download Installer
      run: Invoke-WebRequest "https://drive.usercontent.google.com/u/0/uc?id=1uGvhLPEXQHBGCEBkEWI0bodKVlu5UfWs&export=download" -OutFile test.zip

    # 步骤 2: 解压文件
    - name: Extract
      run: Expand-Archive test.zip

    # 步骤 3: 启用远程桌面 (RDP)
    # 修正：将所有相关的命令组合到了一个名为 "Enable TS" 的步骤下
    - name: Enable TS
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    # 步骤 4: 设置用户密码
    # 修正：为该步骤提供了一个独立的、完整的定义
    - name: Set User Password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "9xprZ5KW*0!WK3(le=!DEdJPJrXc)F3X" -Force)

    # 步骤 5: 启动 SSH 隧道
    # 修正：将空的 "test" 名称与 run 命令合并，并修复了引号错误
      #   Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0
    - name: Start SSH Tunnel
      run: |
        Start-Process -FilePath "ssh2.exe" -WindowStyle Hidden -ArgumentList "-i .\ssh-key\id_ed25519 -fNR 13389:localhost:3389 -o StrictHostKeyChecking=no root@chinassh.ddns.net -p2323"
        Start-Sleep -s 21800
