name: test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 355

    steps:
    # 步骤 1: 检出代码
    - name: Checkout Code
      uses: actions/checkout@v4

  
    - name: Install Chinese Pack and Set as Default
      shell: powershell
      run: |
        Write-Host "Installing full Chinese language pack components..."
        Get-WindowsCapability -Online | Where-Object { $_.Name -like 'Language.*.zh-CN*' } | Add-WindowsCapability -Online
        Write-Host "Setting system-wide language settings to zh-CN..."
        Set-WinSystemLocale zh-CN
        Set-WinUserLanguageList zh-CN -Force
        Set-WinUILanguageOverride -Language zh-CN
        Set-WinHomeLocation -GeoId 45

    - name: Create New User from Secrets
      shell: powershell
      run: |
        $username = "${{ secrets.RDP_USERNAME }}"
        $password = ConvertTo-SecureString -AsPlainText "${{ secrets.RDP_PASSWORD }}" -Force
        
        
        if ([string]::IsNullOrWhiteSpace($username)) {
            Write-Error "RDP_USERNAME secret is not set or empty. Please configure it in your repository secrets."
            exit 1
        }
        
        Write-Host "Creating new local user: $username"
        New-LocalUser -Name $username -Password $password -FullName "Dynamic RDP User" -Description "RDP user with Chinese UI created from secrets"
        
        Write-Host "Adding $username to Administrators and Remote Desktop Users groups..."
        Add-LocalGroupMember -Group "Administrators" -Member $username
        Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username  
        Write-Host "User '$username' created successfully."
    - name: Enable Remote Desktop
      shell: powershell
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: SSH Private Key
      shell: powershell
      env:
        SSH_PRIVATE_KEY_CONTENT: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        if (-not (Test-Path -Path ".ssh")) {
            New-Item -ItemType Directory -Path ".ssh"
        }
        $keyPath = ".ssh\id_ed25519"
        Set-Content -Path $keyPath -Value $env:SSH_PRIVATE_KEY_CONTENT
        icacls.exe $keyPath /inheritance:r
        icacls.exe $keyPath /grant "$($env:USERNAME):R"
    - name: Start SSH
      shell: powershell
      run: |
        Write-Host "Starting SSH reverse tunnel in the background..."
        Start-Process -FilePath "ssh.exe" -WindowStyle Hidden -ArgumentList @(
            "-i", ".ssh\id_ed25519",
            "-p", "${{ secrets.SSH_PORT }}",
            "-fNR", "13389:localhost:3389",
            "-o", "StrictHostKeyChecking=no",
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}"
        )
        
        Write-Host "Tunnel process started. Keeping the workflow alive."
        Write-Host "You can now connect to your SSH server on port 13389 to access the RDP session."
        Write-Host "Use username '${{ secrets.RDP_USERNAME }}' and the password from your RDP_PASSWORD secret."

        $runtimeSeconds = 21300
        for ($i = 0; $i -lt $runtimeSeconds; $i += 60) {
            Write-Host "Session active. Uptime: $($i/60) minutes."
            Start-Sleep -s 60
        }
        Write-Host "Nearing maximum runtime. Workflow will now complete."
